project:
  type: website
  output-dir: docs

website:
  title: "Carlotta Angiolillo"
  navbar:
    left:
      - href: index.qmd
        text: About
      - href: resume.qmd
        text: Resume
      - href: worksamples.qmd
        text: Work Samples

format:
  html:
    theme: journal
    css: styles.css
    toc: true

editor: visual